### ISSUE TITLE
Support for running outside of a browser

### ISSUE THREAD

**Issue by kmudrick** [TimothyRHuertas/normalizer#1]
Currently, feeding normalizer.domString a string to normalize fails when running in a non browser environment (like mocha via node.js) due to missing access to window.document

It would be nice to fall back to using jsdom in this case.

I'll open a pull request for this change shortly.

**Comment by jameswomack** [comment]
Has this issue been rectified @kmudrick ?

**Comment by kmudrick** [comment]
@jameswomack yes, a version or two ago:

 https://github.com/TimothyRHuertas/normalizer/commit/f690b1e8434e057d522d52ef8244830d22a01ac1
