### ISSUE TITLE
Normalizing table fragments

### ISSUE THREAD

**Issue by sdepold** [TimothyRHuertas/normalizer#11]
I have the scenario where I want to take a fragment of a table and normalize it. But passing e.g. a `<tbody>` to the html normalizer makes it throw an error.

Snippet:

```
var Normalizer = require("html-normalizer");
var normalizer = new Normalizer();

normalizer.normalize('<tbody></tbody>')

TypeError: Cannot read property 'nodeType' of undefined
```

The error happens here: https://github.com/TimothyRHuertas/normalizer/blob/master/lib/index.js#L19

The root cause is this line though: https://github.com/TimothyRHuertas/normalizer/blob/master/lib/index.js#L150

It does:

```
var holderNode = document.createElement("div")
holderNode.innerHTML = '<tbody></tbody>'
```

When this happens the div will reject the innerHTML and be empty afterwards causing the following `normalizeHTML` call with `holderNode.children[0]` to fail.

**Comment by TimothyRHuertas** [comment]
Sorry for the delay.  I've been on vacation.  I won't be able to get to this for at least another week.  If you shoot me a pull request I will turn it around within 24 hours.

**Comment by TimothyRHuertas** [comment]
Had some time.  This code seemed to do the trick http://krasimirtsonev.com/blog/article/Revealing-the-magic-how-to-properly-convert-HTML-string-to-a-DOM-element.  Version 7.0.1 should resolve the tbody issue.
