### ISSUE TITLE
Two root siblings are normalized into one element

### ISSUE THREAD

**Issue by sdepold** [TimothyRHuertas/normalizer#12]
The following code 

```
var Normalizer = require("html-normalizer");
var normalizer = new Normalizer();

normalizer.normalize("<div>foo</div><div>bar</div>")
```

generates

```
'<div>bar</div>'
```

In version 6 normalizer was returning the first div, now (v7) it is returning the second/last div. Ideally we would have both though :)

**Comment by TimothyRHuertas** [comment]
Nice catch.  I wrote this with React in mind so the thought of multiple
root nodes slipped my mind.  Merging and publishing now.
