### ISSUE TITLE
Whitelisted classNames consistent comparison?

### ISSUE THREAD

**Issue by kmudrick** [TimothyRHuertas/normalizer#3]
Is there any particular reason that the class names that get checked are not sorted like styles and attributes are?

I think css specificity does not take the order of the classnames into consideration (more so the ordering in the stylesheets), so class='foo bar' and class='bar foo' should be the same

**Comment by TimothyRHuertas** [comment]
Yes.  Order matters for classes; I guess you could argue it matters for styles too (last one wins).  I'm open to changing it.  As I type this response the inconsistent behavior eats at me.  As an aside, you can pass normalizer style or class names to check for (see 'White listing styles and attributes' in the readme).

**Comment by kmudrick** [comment]
I cannot actually find any documentation that says the order of the class names in the class attribute matters: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity 

I do think it should be changed :) I can submit a patch if you'd like

**Comment by TimothyRHuertas** [comment]
Disregard my last message.  It had been a while since I thought about normailzer.  Here is a better reason:

normalizer can tell 
`<div style={{display: none, display: inline}} />`
is equal to 
`<div style={{display: inline}} />`

however it can't tell

`<div className="hide show" />`
is equal to
`<div className="show" />`

``` css
.hide {
  display: none
}

.show {
  display: inline
}
```

**Comment by jameswomack** [comment]
[I've run an experiment that visually demonstrates order in the class attribute doesn't seem to matter.](https://jsfiddle.net/james_womack/x7g9cf88/)

**Comment by kmudrick** [comment]
I merely want to make sure the correct class names are applied:

https://jsfiddle.net/oL0mqa30/

**Comment by kmudrick** [comment]
@jameswomack you wipped that up quick!

**Comment by TimothyRHuertas** [comment]
My last comment was made before I saw yours with the link to specificity.  I was literally was playing with a similar fiddle.  Your are correct and I've been mislead for years...face palm.  I'll happily take the patch.

**Comment by kmudrick** [comment]
@TimothyRHuertas i hate css!

**Comment by kmudrick** [comment]
On a related note, I found this today: https://github.com/bem/html-differ

**Comment by TimothyRHuertas** [comment]
I like it.  Michael Jackson also wrote this
https://github.com/mjackson/expect
Scroll down to the bottom to see a link to the expect-jsx extension
It in tern depends on react-element-to-jsx-string

I mentioned to @sprjr I would cease use of normalizer in favor of MJ's expect (with expect-jsx).  It has more momentum.

**Comment by kmudrick** [comment]
I ended up running into issues with the various chai / expect jsx addons that seemed to stem from incompatible react versions, so I temporarily gave up on them :(

**Comment by kmudrick** [comment]
I think this can be closed now
