### ISSUE TITLE
Blacklist of attributes

### ISSUE THREAD

**Issue by seangates** [TimothyRHuertas/normalizer#6]
Similar to how the whitelist behaves, but the opposite. We only need to blacklist one or two attributes because of some dynamic creation (they will always be different between actual and expected). If we whitelist, we're going to have a very large list which is harder to maintain.

**Comment by jameswomack** [comment]
I like it. If you've not talked to Tim about this yet, I'd say opening a PR is the quickest way to make this happen.

**Comment by seangates** [comment]
Awesome. We already have somewhat of a working example (outside of normalizer). I'll see about getting it working with a PR.

**Comment by TimothyRHuertas** [comment]
Sorry for the delayed response. I've been on vacation in Mexico. I'm going
camping this weekend and won't be back until Tuesday. I like the idea too.
If you open up the request I promise to look at it as soon as I get back.
Of course I trust James or any of the other owners to approve it too.

**Comment by TimothyRHuertas** [comment]
i merged the pull request. Closing this out.

**Comment by TimothyRHuertas** [comment]
Thanks again for the contribution

**Comment by seangates** [comment]
No problem! Thanks for the handy little tool!
